server:
  port: 9000
servlet:
  context-path: /${spring.application.name}
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery: #是否与服务发现组件进行结合，通过 serviceId(必须设置成大写) 转发到具体的服务实例。默认为false，设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能。
        locator:
          enabled: false #开启从注册中心动态创建路由的功能
          lowerCaseServiceId: true #使用小写服务名，默认是大写
      routes:
        - id: gateway-service
          uri: https://www.baidu.com
          predicates:
            - Cookie=sessionId, test

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
    lease-renewal-interval-in-seconds: 5
